import { Product } from './types'

export const productsData: Product[] = [
  {
    id: 1,
    name: 'Sporty baby carrier',
    slug: 'sporty-baby-carrier',
    price: 19.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/sporty.jpeg',
  },
  {
    id: 2,
    name: 'Relaxing baby carrier',
    slug: 'relaxing-baby-carrier',
    price: 29.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/relaxing.jpeg',
  },
  {
    id: 3,
    name: 'Comfy baby carrier',
    slug: 'comfy-baby-carrier',
    price: 14.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/comfy.jpeg',
  },
  {
    id: 4,
    name: 'Lightweight baby carrier',
    slug: 'lightweight-baby-carrier',
    price: 9.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/lightweight.jpeg',
  },
  {
    id: 5,
    name: 'Chill baby carrier',
    slug: 'chill-baby-carrier',
    price: 29.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/chill.jpeg',
  },
  {
    id: 6,
    name: 'Adventurous baby carrier',
    slug: 'adventurous-baby-carrier',
    price: 39.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/adventurous.jpeg',
  },
  {
    id: 7,
    name: 'Durable baby carrier',
    slug: 'durable-baby-carrier',
    price: 59.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/durable.jpeg',
  },
  {
    id: 8,
    name: 'Water proof baby carrier',
    slug: 'water-proof-baby-carrier',
    price: 19.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/water-proof.jpeg',
  },
  {
    id: 9,
    name: 'Travelling baby carrier',
    slug: 'travelling-baby-carrier',
    price: 14.9,
    size: 'Universal size',
    imageUrl: '/products/baby-carrier/travelling.jpeg',
  },
]
